#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#feh --bg-fill ~/Images/wallpaper_alice.jpg
feh --bg-fill ~/Images/wallpaper_alice.jpg --bg-fill ~/Images/oshi\ no\ ko\ wallpaper3.jpg
killall picom;picom &
#killall komorebi;komorebi &

~/.config/polybar/launch-bars.sh

xsetroot -cursor_name Bibata-Modern-Ice
xfce4-power-manager &
killall nm-applet;nm-applet &
killall pasystray;pasystray &
killall polkit-gnome-authentication-agent-1;/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config top_padding 55

bspc config border_width         4
bspc config window_gap           10

# bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# Colors
#"#a9b1d6"
bspc config focused_border_color "#6183bb"
bspc config active_border_color "#006183bb"
bspc config normal_border_color "#00a9b1d6"

# focus window when mouse is over it
bspc config focus_follows_pointer true 

bspc rule -a Firefox desktop='^3'
bspc rule -a VSCodium desktop='^1'
bspc rule -a meast state=floating
